### ISSUE TITLE
Compil error

### ISSUE THREAD

**Issue by TumangShenyon** [wuspy/portal_calendar#26] opened 2024-10-02 09:18 UTC
I got this project to run once (after getting the changes for Rev2.3), and tried to update my Arduino IDE after that.
Now I get some compil error with the [[noreturn]] tag:
```
error: function 'void deepSleep(time_t)' declared '[[noreturn]]' but its first declaration was not
   36 | [[noreturn]] void deepSleep(time_t seconds)
      |                   ^~~~~~~~~
```

I managed to fix it by adding a forward declaration with the noreturn, and removing it from the function, hoping the tag will stay active.
I also needed to update ESPAsyncWebSrv  to 1.2.8

But then I got another problem with the SPI:
`[   526][E][SPI.cpp:116] begin(): Attaching pins to SPI failed.`

Was there a change in the SPI library recently? I don't really know how to fix this, my wiring is still the same.

**Comment by wuspy** [comment] 2024-10-03 07:21
I'm able to reproduce both of these issues. The [[noreturn]] issue can be easily worked around by just removing that tag from all the functions using it in portal_calendar.ino, it's really only for documentation and minor compiler optimization and doesn't actually affect the behavior of the code. I have no idea why the latest version of Arduino IDE has an issue with it.

For the SPI issue... I'm not sure yet. I'll look into it a bit more this week. There's been a new major version of the ESP32 board package released since I last tested this, so that's a likely culprit. Also, I can't reproduce either of these issues in PlatformIO, so if you want to get up and running now you can setup a VSCode + PlatformIO environment and built it with that.

Either way, I do need to actually spend some time testing this with the new major versions of the ESP32 board package and ArduinoJson, and most of my screenshots in the readme are out of date with the latest version of Arduino IDE. So I'll update those in the same MR I (hopefully) fix the SPI issue in.

**Comment by wuspy** [comment] 2024-10-07 04:50
I've opened #27 to address this, if you have time can you check it out and verify if it works for you? It'll probably be a few days before it's merged anyway since I need to do my own testing on it and update the screenshots.

**Comment by wuspy** [comment] 2024-10-08 06:40
After some more testing and noticing weird behavior surrounding time_t values, it looks like Arduino is declaring time_t as 64-bit while PlatformIO is declaring it as 32-bit. This is coming from the different versions of the esp32 toolchain each build system is using, PlatformIO has _WANT_USE_LONG_TIME_T defined however Arduino does not.

My suspicion is that storing this 64-bit time_t in RTC memory corrupts it, as correctSystemClock always prints 0 for timeAsleep, and a garbage value for rtcCorrectionFactor. But I need to look into it more, if I can't develop a workaround I'll update the instructions to install the latest 2.x version of arduino-esp32.

**Comment by wuspy** [comment] 2024-10-08 18:38
Ok so the issue with the 64-bit time_t was purely logging related, I just needed to change the format specifiers. Everything seems to be working across Arduino IDE and PlatformIO now. #27 is updated, I'll probably merge it tomorrow after a bit more testing.

**Comment by TumangShenyon** [comment] 2024-10-09 10:39
Didn't had time to test again in Arduino IDE, but you were right, works well with PlatformIO (never used before, very cool)
I see another typo in a log (or maybe i'm wrong)
time_util.cpp line 154, it's recv and not Result you want to put in the log, right?
Apart from that, great job, i learned so much on esp32 with your code, THKS !

**Comment by wuspy** [comment] 2024-10-09 18:21
Yep you're completely right, I'll update that too.

**Closed as completed** 2024-10-10 03:18 UTC
Labels: bug
